name: Build Documentation using MkDocs

on:  
  push:                            
    paths:                         # Run this action whenever files below change:
    - 'docs/**'                    # - any file under docs                       
    - 'mkdocs.yml'                 # - mkdocs config file
    - '.github/workflows/docs.yml' # - this file

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install mkdocs dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs mkdocs-material mkdocs-minify-plugin

      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy # build docs and deploy to your github project pages
